export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'



export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_ERROR = 'ALERT_ERROR'
export const ALERT_INFO = 'ALERT_INFO'
export const CLOSE_ALERT = 'CLOSE_ALERT'


export const PATH_NEW = 'PATH_NEW'
export const PATH_ADD = 'PATH_ADD'



export const SHOW_MAIL_CONFIRM_FALSE = 'SHOW_MAIL_CONFIRM_FALSE'

export const SHOW_MAIL_CONFIRM_TRUE = 'SHOW_MAIL_CONFIRM_TRUE'








export const SET_MAIN_PATH = 'SET_MAIN_PATH'





